In [1]:
!pip install vega
!jupyter nbextension install --sys-prefix --py vega

Requirement already satisfied: vega in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (3.5.0)
Requirement already satisfied: jupyter<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from vega) (1.0.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from vega) (1.2.4)
Requirement already satisfied: jupyter-console in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (6.4.0)
Requirement already satisfied: ipywidgets in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (7.6.3)
Requirement already satisfied: ipykernel in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (5.5.5)
Requirement already satisfied: qtconsole in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (5.1.1)
Requirement already satisfied: nbconvert in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (6.0.7)
Requirement already satisfied: notebook in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->vega) (6.4.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas<2.0.0,>=1.0.0->vega) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas<2.0.0,>=1.0.0->vega) (1.19.5)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas<2.0.0,>=1.0.0->vega) (2021.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.0.0->vega) (1.15.0)
Requirement already satisfied: traitlets>=4.1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (5.0.5)
Requirement already satisfied: ipython>=5.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (7.24.1)
Requirement already satisfied: tornado>=4.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (6.1)
Requirement already satisfied: appnope in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.1.2)
Requirement already satisfied: jupyter-client in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->vega) (6.1.12)
Requirement already satisfied: matplotlib-inline in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.1.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (3.0.19)
Requirement already satisfied: backcall in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.18.0)
Requirement already satisfied: pickleshare in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (49.2.1)
Requirement already satisfied: pexpect>4.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (4.8.0)
Requirement already satisfied: decorator in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (5.0.9)
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (2.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.8.2)
Requirement already satisfied: ptyprocess>=0.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.7.0)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.2.5)
Requirement already satisfied: ipython-genutils in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from traitlets>=4.1.0->ipykernel->jupyter<2.0.0,>=1.0.0->vega) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->vega) (5.1.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->vega) (3.5.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->vega) (1.0.0)
Requirement already satisfied: jupyter-core in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->vega) (4.7.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->vega) (3.2.0)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->vega) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter<2.0.0,>=1.0.0->vega) (0.17.3)
Requirement already satisfied: terminado>=0.8.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (0.10.1)
Requirement already satisfied: argon2-cffi in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (20.1.0)
Requirement already satisfied: Send2Trash>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (1.5.0)
Requirement already satisfied: prometheus-client in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (0.11.0)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (3.0.1)
Requirement already satisfied: pyzmq>=17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->vega) (22.1.0)
Requirement already satisfied: cffi>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->vega) (1.14.5)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->vega) (2.20)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jinja2->notebook->jupyter<2.0.0,>=1.0.0->vega) (2.0.1)

Requirement already satisfied: entrypoints>=0.2.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.3)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.5.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.4.3)
Requirement already satisfied: bleach in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (3.3.0)
Requirement already satisfied: testpath in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.5.0)
Requirement already satisfied: jupyterlab-pygments in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.8.4)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.7.1)
Requirement already satisfied: async-generator in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.10)
Requirement already satisfied: nest-asyncio in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (1.5.1)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bleach->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (20.9)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bleach->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from packaging->bleach->nbconvert->jupyter<2.0.0,>=1.0.0->vega) (2.4.7)
Requirement already satisfied: qtpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from qtconsole->jupyter<2.0.0,>=1.0.0->vega) (1.9.0)
WARNING: You are using pip version 21.1.2; however, version 21.2.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
Installing /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/vega/static -> jupyter-vega
Up to date: /Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/nbextensions/jupyter-vega/widget.js.map
Up to date: /Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/nbextensions/jupyter-vega/index.js
Up to date: /Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/nbextensions/jupyter-vega/widget.js
Up to date: /Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/nbextensions/jupyter-vega/vega.js
Up to date: /Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/nbextensions/jupyter-vega/index.js.map
Up to date: /Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/nbextensions/jupyter-vega/index.js.LICENSE.txt
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable vega --py --sys-prefix

In [2]:
# Import the needed dependencies below.
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import altair as alt # graphical representation tool

# alt.renderers.enable('notebook')
alt.renderers.enable('default')

RendererRegistry.enable('default')

In [3]:
netflix_movies = pd.read_csv('netflix_titles.csv')
netflix_stocks = pd.read_csv('NFLX.csv')

In [4]:
netflix_movies = netflix_movies[netflix_movies['type']=='Movie'].dropna()
netflix_movies.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
6,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,TV-MA,95 min,"Horror Movies, International Movies","After an awful accident, a couple admitted to ..."

In [5]:
netflix_stocks.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  2002-05-23  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
1  2002-05-24  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2  2002-05-28  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
3  2002-05-29  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
4  2002-05-30  1.107857  1.107857  1.071429  1.071429   1.071429   10154200

Now, that we have our DataFrames ready; we can continue to doing some investigative work. Let's check the descriptive statistics for both stocks and a couple different segmentations for movies with pd.DataFrame.describe().

In [6]:
netflix_movies.date_added = pd.to_datetime(netflix_movies.date_added)
movies_over_time = netflix_movies.copy().groupby('release_year')['title'].count().reset_index()
movies_over_time = movies_over_time.rename(columns={0:'count'})

median_year = int(netflix_movies ['release_year'].median()) #2016
mode_year = int(netflix_movies ['release_year'].mode())
print("this is the median:", median_year, ", this is the mode:", mode_year)
movies_over_time.describe()

this is the median: 2016 , this is the mode: 2017

       release_year       title
count     71.000000   71.000000
mean    1985.295775   65.816901
std       21.827502  140.246040
min     1942.000000    1.000000
25%     1968.500000    3.000000
50%     1986.000000    9.000000
75%     2003.500000   39.000000
max     2021.000000  627.000000

In [7]:
netflix_stocks['Date'] = pd.to_datetime(netflix_stocks['Date'])

netflix_stocks.describe()

,Open,High,Low,Close,Adj Close,Volume
count,4581.000000,4581.000000,4581.000000,4581.000000,4581.000000,4.581000e+03
mean,78.031471,79.285690,76.736079,78.072056,78.072056,1.760516e+07
std,118.372084,120.276839,116.376768,118.435303,118.435303,1.971130e+07
min,0.377857,0.410714,0.346429,0.372857,0.372857,2.856000e+05
25%,3.778571,3.857143,3.685714,3.784286,3.784286,6.908900e+06
50%,15.392858,15.671429,14.970000,15.324286,15.324286,1.155350e+07
75%,97.830002,99.529999,96.760002,97.889999,97.889999,2.113440e+07
max,567.979980,575.369995,520.960022,548.729980,548.729980,3.234140e+08

We get to see our maxes and mins & highs and lows. We have a pretty good idea of the distribution for the movies and the average closing dollar amount. Could Netflix releases over the years correlated with the stock price? Can we tell if our answer is statistically significant?

If you think about releases, there are four elements of releases that might catch a movie lover's attention. You have:
1. Main film location:  language matters but relativity to the elements in the movie and being familiar with the references is quentissential in most instances. 
2. Director: we all have our favorite director. It's the movie that was most memorable or the one that made you laugh the most. You loved the cinamatic touches they added. You strap in for a good movie when you hear what's on for movie night.
3. Actor: Leonardo DiCaprio gets my buy in on any movie. We all have that person of a few! Is their a primary actor driving the market?
4. Genre: I love a good horror movie, don't you? Not your forte? Let's see if the genres of the movie releases and the stock price have a relationship.

These ideas are all speculative, but I invite my readers to stay the course. The insights and graphs are at the bottom. Continue reading if you'd like.

In [8]:
# Assuming the first movie listed is where this movie was filmed the most, we will replace the lists of movies
# with the first country and use that to find the top 10 countries that have movies are currently on Netflix 

movies_with_countries = netflix_movies.copy()
new=movies_with_countries['country'].str.split(',', n=5, expand=True)
countries = [('1st',0), ('2nd',1),('3rd',2),('4th',3),('5th',4),('6th',5)]
for i in countries:
    movies_with_countries[i[0]+" country"] = new[i[1]]
new_mwc = movies_with_countries.drop(columns=['show_id','type','director','cast'])
distribution_df = new_mwc[['1st country',
                                         'title']].groupby(
    '1st country'
).count().reset_index()
distribution_df.head()

  1st country  title
0   Argentina     45
1   Australia     49
2     Austria      5
3  Bangladesh      2
4     Belgium      5

We could say Hollywood knows how to make a good movie? Or should we say that one director is taking center stage and we just can't get enough?

In [9]:
directors = movies_with_countries.copy()
directors = directors[directors['country']=='United States'][['director','title','rating','listed_in']]
directors.head()


new_dir = directors['director'].str.split(',', n=2, expand=True)
split = [('1st',0), ('2nd',1)]

# How has the 
for i in split:
    directors[i[0]+" Named Director"] = new_dir[i[1]]
top_directors = directors[['1st Named Director','title','rating','listed_in']].groupby(
    '1st Named Director'
)['title'].count().reset_index()


top_directors[top_directors['title']==top_directors.title.max()]

    1st Named Director  title
495          Jay Karas     15

Let's be honest, Jay Karas is taking the market by storm with his work in comedy, so this one isn't too much of a surprise! Let's look for other trends that are in the data. Later, we will investigate if there is a correlation between the movies released and the stock price. We can't say conclusively that there is a direct cause and effect relationship; it's interested to find patterns in data, just for fun!

Now, we have to ask, *does the year a movie was released matter?* I can imagine that there have been times that the film industry took a hit and not too many movies reached production. We can only speculate about the greater implications. It could just mean that the most popular year had the best movies. We decide what this metric becomes in the end!

In [17]:
titles_per_country = alt.Chart(distribution_df,
                              height=300,
                              width=500,
                              title='Number of Titles per Country').transform_window(
    rank='rank(title)',
    sort=[alt.SortField('title', order='descending')]
).transform_filter(
    alt.datum.rank <=10
).mark_bar(color='red').encode(
    y=alt.Y('title:Q',
           axis=alt.Axis(title='Number of Movies',
                         tickCount=4,
                         labelPadding=10,
                        titlePadding=10)),
    x=alt.X('1st country:N',
           sort=alt.EncodingSortField('title',order='descending'),
           title=None,
           axis=alt.Axis(
                        labelAngle=-45,
               labelFontSize=15
           )),
    color=alt.condition(
        alt.datum.rank == 1,
        alt.value('red'),
        alt.value('black')
    ),
    tooltip=['1st country:N', 'title']
)

titles_per_country

alt.Chart(...)

In [19]:
titles_by_year = alt.Chart(movies_over_time,
                              height=300,
                              width=500,
                              title='Number of Titles by Year').transform_window(
    rank='rank(title)',
    sort=[alt.SortField('title', order='descending')]
).transform_filter(
    alt.datum.rank <=10
).mark_bar(color='red').encode(
    y=alt.Y('title:Q',
           axis=alt.Axis(title='Number of Movies',
                         tickCount=4,
                         labelPadding=10,
                        titlePadding=10)),
    x=alt.X('release_year:N',
           sort=alt.EncodingSortField('title',order='descending'),
           title=None,
           axis=alt.Axis(
                        labelAngle=-45,
               labelFontSize=15
           )),
    color=alt.condition(
        alt.datum.rank == 1,
        alt.value('red'),
        alt.value('black')
    ),
    tooltip=['release_year:N', 'title']
)

titles_by_year

alt.Chart(...)